### PR TITLE
add kubeedge and karmada cncf project

### PR DESCRIPTION
**Pull request by kerthcet**
Signed-off-by: kerthcet <kerthcet@gmail.com>

Kubeedge and karmada are cncf projects, I think it's suitable to merge them into the project.

### CODE REVIEW

**Comment by kerthcet** [comment]
kindly ping @aostapenko

**Comment by kerthcet** [comment]
I wonder whether anyone is still concern about this?

**Comment by Abirdcfly** [comment]
https://opendev.org/x/stackalytics/src/branch/master  I find this.

**Comment by kerthcet** [comment]
> https://opendev.org/x/stackalytics/src/branch/master I find this.

Thanks, it seems an active project.

**Pull request closed without merging**
