### PR TITLE
Add Rancher Labs users

### PR DESCRIPTION
**Pull request by cjellick**
Employees at Rancher that haven't been using their Rancher email

### CODE REVIEW

**Comment by cjellick** [comment]
cc @leodotcloud @erikwilson @aiwantaozi @gitlawr @rmweir

**Comment by leodotcloud** [comment]
Thank you @cjellick for taking care of this!

**Comment by niksv** [comment]
@cjellick Please fix merge conflicts

**Comment by cjellick** [comment]
done @niksv. thanks!

**Pull request merged**
