### PR TITLE
add new user: wzshiming & mengjiao-liu

### PR DESCRIPTION
**Pull request by pacoxu**
Add a member who will work on kubernetes.

### CODE REVIEW

**Comment by pacoxu** [comment]
@wzshiming 
@niksv

**Comment by pacoxu** [comment]
kindly ping @niksv as this pr is not updated for a month.

**Comment by wzshiming** [comment]
Hi @niksv, Is this project still maintained?

**Comment by wzshiming** [comment]
ping @niksv

**Comment by niksv** [comment]
Sorry but I'm not working on stackalytics anymore. 
But there is another site https://www.stackalytics.io/
Andrii Ostapenko (aostapenko@stackalytics.io) is working on it right now. To add some changes to stackalytics.io you need to create patch like https://review.opendev.org/c/x/stackalytics/+/776859
Please contact Andrii if any trouble

**Pull request closed without merging**
