### PR TITLE
Add Futurewei company affiliation

### PR DESCRIPTION
**Pull request by mriedem**
End the Huawei and start the Futurewei company
affiliation for:

* Matt Riedemann
* Melvin Hillsman
* Lance Bragstad
* Sean McGinnis
* Davanum Srinivas

Since Sean and Melvin had huawei emails registered
their futurewei email is added.

### CODE REVIEW

**Comment by mrhillsman** [comment]
ack @mriedem

**Comment by stmcginnis** [comment]
Thanks Matt, this looks correct to me.

**Comment by lbragstad** [comment]
lgtm - thanks @mriedem

**Comment by mriedem** [comment]
I'm honestly not sure if I should be updating this file or this one:

https://opendev.org/x/stackalytics/src/branch/master/etc/default_data.json

The wiki says this repo though:

https://wiki.openstack.org/wiki/Stackalytics#Company_affiliation

But maybe that wiki is old? @niksv can you clarify?

**Comment by dims** [comment]
Thanks @mriedem

**Comment by niksv** [comment]
@mriedem At this moment stackalytics.com gets default_data directly from this repo https://github.com/stackalytics/default_data.
So the most fast way to deliver you updates to the stackalytics is to create a PR here. 
But all patches to the https://opendev.org/x/stackalytics/src/branch/master/etc/default_data.json are also valid. I'm copy updated data from https://opendev.org/x/stackalytics/ to https://github.com/stackalytics/ periodically

**Comment by mriedem** [comment]
Ack thanks Sergey.

**Pull request merged**
