### PR TITLE
add my_count company_name

### PR DESCRIPTION
**Pull request by 928234269**
Signed-off-by: 928234269 <longfei.shang@daocloud.io>

### CODE REVIEW

**Comment by 928234269** [comment]
@ytinirt  @dreadbird  @Wavez  @mkowalski  hello everyone.  I really need to increase my account signal, who can help me merge this Pr.

**Comment by Wavez** [comment]
> @ytinirt @dreadbird @Wavez @mkowalski hello everyone. I really need to increase my account signal, who can help me merge this Pr.

I'm no admin here bruh but it looks good to me so +1 👌

**Comment by 928234269** [comment]
who can help me? @ytinirt @dreadbird @mkowalski

**Comment by 928234269** [comment]
@niksv Can you help me merge this pr? I really need it.

**Comment by niksv** [comment]
sure

**Pull request merged**
